channel_sources:
- adrianinsaval,freecad/label/dev,conda-forge,defaults
channel_targets:
- adrianinsaval dev
MACOSX_DEPLOYMENT_TARGET:  # [osx]
- '11.0'                  # [osx and arm64]
- '10.12'                  # [osx and not arm64]