macos_task:
    # Basic metadata:
    name: build_osx_arm64_python3.10.____cpython

    # The build machine:
    macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-xcode:13

    # Environment variables:
    env:
        CONFIG: osx_arm64_python3.10.____cpython
        UPLOAD_PACKAGES: True
        BINSTAR_TOKEN: ENCRYPTED[71b42877c923177f43cad29750c6116c3a7d1d543409d5028dedfffa9c40307e2fe100ffb0a895858fe635b1c33c5842]

    # Instructions:
    osx_build_script: |
        export CI=cirrus
        export FEEDSTOCK_NAME=$(basename ${CIRRUS_REPO_NAME})
        if [ -z "$CIRRUS_PR" ]; then
          export IS_PR_BUILD="False"
        else
          export IS_PR_BUILD="True"
        fi
        ./.scripts/run_osx_build.sh

linux_task:
    # Basic metadata:
    name: build_linux_aarch64_python3.10.____cpython

    # The build machine:
    arm_container:
        image: ghcr.io/actions/actions-runner-controller/actions-runner:ubuntu-20.04
        cpu: 4
        memory: 8G
        kvm: true

    # Environment variables:
    env:
        CONFIG: linux_aarch64_python3.10.____cpython
        UPLOAD_PACKAGES: True
        BINSTAR_TOKEN: ENCRYPTED[71b42877c923177f43cad29750c6116c3a7d1d543409d5028dedfffa9c40307e2fe100ffb0a895858fe635b1c33c5842]
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-aarch64

    # Instructions:
    docker_build_script: |
        export CI=cirrus
        export FEEDSTOCK_NAME=$(basename ${CIRRUS_REPO_NAME})
        if [ -z "$CIRRUS_PR" ]; then
          export IS_PR_BUILD="False"
        else
          export IS_PR_BUILD="True"
        fi
        ./.scripts/run_docker_build.sh