task:
    # Basic metadata:
    name: conda
    only_if: true

    # The build machine:
    macos_instance:
        image: ghcr.io/cirruslabs/macos-monterey-xcode:13

    # Environment variables:
    env:
        CONFIG: osx_arm64_python3.10.____cpython
        UPLOAD_PACKAGES: True

    # Instructions:
    build_osx_script: |
        export CI=cirrus
        export FEEDSTOCK_NAME=$(basename ${CIRRUS_REPO_NAME})
        if [ -z "$CIRRUS_PR" ]; then
          export IS_PR_BUILD="False"
        else
          export IS_PR_BUILD="True"
        fi
        ./.scripts/run_osx_build.sh
