provider:
  win: gtihub_actions
  linux: gtihub_actions
  linux_aarch64: circle
  osx_64: gtihub_actions
  osx_arm64: circle
build_platform:
  osx_arm64: osx_arm64
  linux_aarch64: linux_aarch64
test_on_native_only: true
